---
- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: install package dependencies for aiida installation
  become: true
  package:
    name: "{{ aiida_package_dependencies }}"
    state: present

- name: check virtual environment with conda env list
  shell: bash -lc "conda env list"
  register: conda_check_env
  changed_when: false
  failed_when: conda_check_env.rc != 0

- when: conda_check_env.stdout is not search(aiida_env_name)
  block:
    - name: generate environment.yml
      template:
        src: "environment.yml.j2"
        dest: "/tmp/environment.yml"
        mode: 0644
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: create conda virtual environment
      shell: bash -lc "conda env update --file /tmp/environment.yml"
      register: conda_create_env
      changed_when: "conda_create_env.stdout is not search('CondaValueError: prefix already exists')"
      failed_when: conda_check_env.rc != 0

- name: delete environment.yml
  file:
    path: "/tmp/environment.yml"
    state: absent

- name: create aiidadb database
  become: yes
  become_user: postgres
  postgresql_db:
    name: aiidadb
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    encoding: 'UTF-8'
    template: 'template0'
    owner: aiida
    port: 5432
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true

- name: grant privileges for aiida user on aiidadb database
  become: yes
  become_user: postgres
  postgresql_privs:
    db: aiidadb
    port: 5432
    privs: ALL
    type: database
    role: aiida

- name: set password for aiida user with no expire date on aiidadb database
  become: yes
  become_user: postgres
  postgresql_user:
    db: aiidadb
    name: aiida
    port: 5432
    encrypted: yes
    password: "{{ aiida_aiidadb_password | default(omit) }}"
    expires: infinity
...
