---
- name: Update apt cache
  become: true
  apt:
    update_cache: true
    cache_valid_time: 86400
  when: ansible_os_family == 'Debian'

- name: Include OS-specific variables (Debian)
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Debian"

- name: Install AiiDA dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ aiida_installation_dependencies }}"
  when: ansible_os_family == 'Debian'

- name: Install AiiDA using pip
  pip:
    name: "{{ item }}"
    virtualenv: "{{ ansible_env.HOME }}/aiidapy"
    virtualenv_python: python2.7
  with_items:
    - "aiida"
...
