---
- name: Update apt cache
  become: true
  apt:
    update_cache: true
    cache_valid_time: 86400
  when: ansible_os_family == 'Debian'

- name: Include OS-specific variables (Debian)
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Debian"

- name: Install AiiDA dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ aiida_install_from_source_dependencies }}"
  when: ansible_os_family == 'Debian'
...
